export type SortField = 'modelName' | "name" | "email" | "role" | "event" | "type" | "enabled" | "supervisor" | "location" | "lastname" | "phone" | "date";
export type SortOrder = "asc" | "desc";
export type ViewMode =
    | "users"
    | "roles"
    | "permissions"
    | "add-user"
    | "agents"
    | "add-agent"
    | "edit-agent"
    | "agent-details"
    | "add-role"
    | "add-permission"
    | "user-details"
    | "role-details"
    | "permission-details"
    | "checklists"
    | "add-checklist"
    | "checklist-details"
    | "reasons"
    | "add-reason"
    | "reason-details"
    | "notification-rules"
    | "notification-rule-details"
    | "add-notification-rule"
    | "notifications"
    | "ai-configs"
    | "add-ai-config"
    | "ai-config-details"
    | "edit-ai-config"
