const ReportService = require('../services/reportService');
const NotificationService = require('../services/notificationService');
const { ReportSchedule, GeneratedReport, User } = require('../models');
const cron = require('node-cron');
const path = require('path');
const fs = require('fs').promises;
const { sequelize } = require('../config/db');
const Sequelize = require('sequelize');
const { getRedisClient } = require('../config/redis');
const RedisUtils = require('../utils/redisUtils');
const cache = require('../utils/cache');
const { v4: uuidv4 } = require('uuid');
const { logRequest } = require('../utils/controllerUtils');


class ReportController {
    static validReportTypes = [
        'VisitSummary',
        'Timesheet',
        'ReceiptBookInventory',
        'StubCollection',
        'UserActivity',
        'Anomaly',
        'AgentPerformance',
        'RegionPerformance',
        'Full'
    ];

    static validFormats = ['pdf', 'excel'];

    static validateInput(reportType, format, cronExpression) {
        if (!this.validReportTypes.includes(reportType)) {
            throw new Error('Invalid report type');
        }
        if (!this.validFormats.includes(format)) {
            throw new Error('Invalid format. Use "pdf" or "excel"');
        }
        if (cronExpression && !cron.validate(cronExpression)) {
            throw new Error('Invalid cron expression');
        }
    }

    static async generateReport(req, res) {
        const transaction = await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_COMMITTED });
        const { reportType, filters = {}, format } = req.body;

        try {
            const userId = req.user?.userID;
            if (!userId) {
                await transaction.rollback();
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            ReportController.validateInput(reportType, format);

            const reportMethod = {
                'VisitSummary': ReportService.generateVisitSummaryReport,
                'Timesheet': ReportService.generateTimesheetReport,
                'ReceiptBookInventory': ReportService.generateReceiptBookInventoryReport,
                'StubCollection': ReportService.generateStubCollectionReport,
                'UserActivity': ReportService.generateUserActivityReport,
                'Anomaly': ReportService.generateAnomalyReport,
                'AgentPerformance': ReportService.generateAgentPerformanceReport,
                'RegionPerformance': ReportService.generateRegionPerformanceReport,
                'Full': ReportService.generateFullReport
            }[reportType];

            if (!reportMethod || typeof reportMethod !== 'function') {
                await transaction.rollback();
                throw new Error(`Invalid report method for reportType: ${reportType}`);
            }

            const data = await reportMethod(filters);
            const filePath = await ReportService.exportReport(reportType, data, format);
            const fileName = path.basename(filePath);

            await GeneratedReport.create({
                reportType,
                format,
                filePath: fileName,
                generatedBy: userId
            }, { transaction });
            const user = await User.findByPk(userId);

            const cacheInstance = await cache();
            const redis = getRedisClient();
            await cacheInstance.invalidateByTag('reports');
            await redis.set('reports:last_updated', Date.now().toString());
            await RedisUtils.publishEvent('cache:invalidate', 'reports');

            const requestID = uuidv4();
            await NotificationService.triggerNotification({
                event: 'report:generated',
                data: { reportType, format, filters },
                metadata: { triggeredBy: req.user?.email || 'unknown' },
                dynamicRecipients: [],
                triggeredByUserID: userId,
                type: 'report',
                customMessage: `Report ${reportType} generated by user ${user.firstname} ${user.lastname}`,
                requestID,
            });

            logRequest({
                req,
                res: { message: 'Report generated successfully', reportPath: `/api/reports/download?file=${fileName}` },
                status: 200,
                message: `Generated ${reportType} report`,
                level: 'info',
                metadata: { reportType, format, file: fileName, userId, requestID },
                service: 'report',
                defaultRoute: 'reports'
            });

            await transaction.commit();
            return res.status(200).json({
                message: 'Report generated successfully',
                reportPath: `/api/reports/download?file=${fileName}`
            });
        } catch (error) {
            await transaction.rollback();
            logRequest({
                req,
                error,
                status: 400,
                message: `Failed to generate ${reportType} report: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(400).json({ error: error.message });
        }
    }

    static async scheduleReport(req, res) {
        const transaction = await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_COMMITTED });
        const { reportType, filters = {}, format, cronExpression } = req.body;

        try {
            const userId = req.user?.userID;
            if (!userId) {
                await transaction.rollback();
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            ReportController.validateInput(reportType, format, cronExpression);

            const schedule = await ReportSchedule.create({
                reportType,
                filters: JSON.stringify(filters),
                format,
                cronExpression,
                createdBy: userId
            }, { transaction });

            cron.schedule(cronExpression, async () => {
                const cronTransaction = await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_COMMITTED });
                try {
                    const currentSchedule = await ReportSchedule.findByPk(schedule.scheduleID);
                    if (!currentSchedule) {
                        await cronTransaction.commit();
                        logRequest({
                            req: null,
                            status: 200,
                            message: `Schedule ${schedule.scheduleID} no longer exists`,
                            level: 'info',
                            service: 'report',
                            defaultRoute: 'reports'
                        });
                        return;
                    }

                    const reportMethod = {
                        'VisitSummary': ReportService.generateVisitSummaryReport,
                        'Timesheet': ReportService.generateTimesheetReport,
                        'ReceiptBookInventory': ReportService.generateReceiptBookInventoryReport,
                        'StubCollection': ReportService.generateStubCollectionReport,
                        'UserActivity': ReportService.generateUserActivityReport,
                        'Anomaly': ReportService.generateAnomalyReport,
                        'AgentPerformance': ReportService.generateAgentPerformanceReport,
                        'RegionPerformance': ReportService.generateRegionPerformanceReport,
                        'Full': ReportService.generateFullReport
                    }[reportType];

                    const data = await reportMethod(filters);
                    const filePath = await ReportService.exportReport(reportType, data, format);
                    const fileName = path.basename(filePath);

                    await GeneratedReport.create({
                        reportType,
                        format,
                        filePath: fileName,
                        scheduleID: schedule.scheduleID
                    }, { transaction: cronTransaction });

                    const cacheInstance = await cache();
                    const redis = getRedisClient();
                    await cacheInstance.invalidateByTag('reports');
                    await redis.set('reports:last_updated', Date.now().toString());
                    await RedisUtils.publishEvent('cache:invalidate', 'reports');

                    const cronRequestID = uuidv4();
                    await NotificationService.triggerNotification({
                        event: 'report:generated',
                        data: { reportType, format, fileName },
                        metadata: { scheduleID: schedule.scheduleID },
                        dynamicRecipients: [],
                        triggeredByUserID: userId,
                        type: 'report',
                        customMessage: `Scheduled report ${reportType} generated `,
                        requestID: cronRequestID,
                    });

                    logRequest({
                        req: null,
                        status: 200,
                        message: `Scheduled ${reportType} report generated`,
                        level: 'info',
                        metadata: { reportType, scheduleID: schedule.scheduleID, requestID: cronRequestID },
                        service: 'report',
                        defaultRoute: 'reports'
                    });

                    await cronTransaction.commit();
                } catch (error) {
                    await cronTransaction.rollback();
                    logRequest({
                        req: null,
                        status: 500,
                        message: `Scheduled ${reportType} report failed: ${error.message}`,
                        level: 'error',
                        metadata: { reportType, scheduleID: schedule.scheduleID, error: error.message },
                        service: 'report',
                        defaultRoute: 'reports'
                    });
                }
            });
            const user = await User.findByPk(userId);

            const requestID = uuidv4();
            await NotificationService.triggerNotification({
                event: 'report:scheduled',
                data: { reportType, format, cronExpression, scheduleID: schedule.scheduleID },
                metadata: { triggeredBy: req.user?.email || 'unknown' },
                dynamicRecipients: [],
                triggeredByUserID: userId,
                type: 'report',
                customMessage: `Report ${reportType} scheduled by user ${user.firstname} ${user.lastname}`,
                requestID,
            });

            logRequest({
                req,
                res: { message: 'Report scheduled successfully', scheduleID: schedule.scheduleID },
                status: 200,
                message: `Scheduled ${reportType} report`,
                level: 'info',
                metadata: { userId, scheduleID: schedule.scheduleID, requestID },
                service: 'report',
                defaultRoute: 'reports'
            });

            await transaction.commit();
            return res.status(200).json({
                message: 'Report scheduled successfully',
                scheduleID: schedule.scheduleID
            });
        } catch (error) {
            await transaction.rollback();
            logRequest({
                req,
                error,
                status: 400,
                message: `Failed to schedule ${reportType} report: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(400).json({ error: error.message });
        }
    }

    static async downloadReport(req, res) {
        try {
            const { file } = req.query;
            const userId = req.user?.userID;
            if (!userId) {
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            if (!file || typeof file !== 'string') {
                logRequest({
                    req,
                    status: 400,
                    message: 'Valid file name is required',
                    level: 'info',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(400).json({ error: 'Valid file name is required' });
            }

            const fileName = path.basename(file);
            const filePath = path.join(__dirname, '../reports', fileName);

            try {
                await fs.access(filePath);
            } catch {
                logRequest({
                    req,
                    status: 404,
                    message: 'Report file not found',
                    level: 'info',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(404).json({ error: 'Report file not found' });
            }

            res.download(filePath, fileName, (err) => {
                if (err) {
                    if (!res.headersSent) {
                        logRequest({
                            req,
                            error: err,
                            status: 500,
                            message: `Failed to download report ${fileName}: ${err.message}`,
                            level: 'error',
                            service: 'report',
                            defaultRoute: 'reports'
                        });
                        res.status(500).json({ error: 'Failed to download report' });
                    }
                } else {
                    logRequest({
                        req,
                        status: 200,
                        message: `Successfully downloaded report ${fileName}`,
                        level: 'info',
                        metadata: { userId, file: fileName },
                        service: 'report',
                        defaultRoute: 'reports'
                    });
                }
            });
        } catch (error) {
            const status = error.message.includes('not found') ? 404 : 400;
            logRequest({
                req,
                error,
                status,
                message: `Failed to download report: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(status).json({ error: error.message });
        }
    }

    static async listSchedules(req, res) {
        try {
            const userId = req.user?.userID;
            if (!userId) {
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            const cacheInstance = await cache();
            const schedules = await cacheInstance.getOrSet(`report:schedules:${userId}`, async () => {
                return await ReportSchedule.findAll({
                    attributes: ['scheduleID', 'reportType', 'format', 'cronExpression', 'createdBy', 'createdAt'],
                    include: [{
                        model: User,
                        attributes: ['userID', 'firstname', 'lastname'],
                        as: 'Creator'
                    }]
                });
            }, 'api');

            logRequest({
                req,
                res: schedules,
                status: 200,
                message: `Listed ${schedules.length} report schedules`,
                level: 'info',
                metadata: { userId, count: schedules.length },
                service: 'report',
                defaultRoute: 'reports'
            });

            return res.status(200).json(schedules);
        } catch (error) {
            logRequest({
                req,
                error,
                status: 500,
                message: `Failed to list schedules: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(500).json({ error: 'Failed to list report schedules' });
        }
    }

    static async listGeneratedReports(req, res) {
        try {
            const userId = req.user?.userID;
            if (!userId) {
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            const cacheInstance = await cache();
            const reports = await cacheInstance.getOrSet(`report:generated:${userId}`, async () => {
                return await GeneratedReport.findAll({
                    attributes: ['generatedReportID', 'reportType', 'format', 'filePath', 'generatedAt', 'generatedBy', 'scheduleID'],
                    include: [
                        {
                            model: User,
                            attributes: ['userID', 'firstname', 'lastname'],
                            as: 'Generator'
                        },
                        {
                            model: ReportSchedule,
                            attributes: ['scheduleID', 'reportType', 'format', 'cronExpression'],
                            as: 'Schedule'
                        }
                    ],
                    order: [['generatedAt', 'DESC']]
                });
            }, 'api');

            logRequest({
                req,
                res: reports,
                status: 200,
                message: `Listed ${reports.length} generated reports`,
                level: 'info',
                metadata: { userId, count: reports.length },
                service: 'report',
                defaultRoute: 'reports'
            });

            return res.status(200).json(reports);
        } catch (error) {
            logRequest({
                req,
                error,
                status: 500,
                message: `Failed to list generated reports: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(500).json({ error: 'Failed to list generated reports' });
        }
    }

    static async deleteSchedule(req, res) {
        const transaction = await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_COMMITTED });
        try {
            const { scheduleID } = req.params;
            const userId = req.user?.userID;
            if (!userId) {
                await transaction.rollback();
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            const schedule = await ReportSchedule.findByPk(scheduleID);
            if (!schedule) {
                await transaction.rollback();
                logRequest({
                    req,
                    status: 404,
                    message: `Schedule ${scheduleID} not found`,
                    level: 'info',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(404).json({ error: 'Schedule not found' });
            }

            const reportSchedule = await ReportSchedule.findByPk(scheduleID);
            await schedule.destroy({ transaction });
            const user = await User.findByPk(userId);

            const cacheInstance = await cache();
            const redis = getRedisClient();
            await cacheInstance.invalidateByTag('reports');
            await cacheInstance.invalidate(`report:schedules:${userId}`);
            await redis.set('reports:last_updated', Date.now().toString());
            await RedisUtils.publishEvent('cache:invalidate', 'reports');

            const requestID = uuidv4();
            await NotificationService.triggerNotification({
                event: 'report_schedule:deleted',
                data: { scheduleID },
                metadata: { deletedBy: req.user?.email || 'unknown' },
                dynamicRecipients: [],
                triggeredByUserID: userId,
                type: 'report',
                customMessage: `Report schedule ${reportSchedule.reportType} deleted by user ${user.firstname} ${user.lastname}`,
                requestID,
            });

            logRequest({
                req,
                res: { message: 'Schedule deleted successfully' },
                status: 200,
                message: `Deleted schedule ${scheduleID}`,
                level: 'info',
                metadata: { userId, scheduleID, requestID },
                service: 'report',
                defaultRoute: 'reports'
            });

            await transaction.commit();
            return res.status(200).json({ message: 'Schedule deleted successfully' });
        } catch (error) {
            await transaction.rollback();
            logRequest({
                req,
                error,
                status: 500,
                message: `Failed to delete schedule: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(500).json({ error: 'Failed to delete schedule' });
        }
    }

    static async deleteGeneratedReport(req, res) {
        const transaction = await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_COMMITTED });
        try {
            const { reportID } = req.params;
            const userId = req.user?.userID;
            if (!userId) {
                await transaction.rollback();
                logRequest({
                    req,
                    status: 401,
                    message: 'Unauthorized: User ID missing',
                    level: 'error',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(401).json({ error: 'Unauthorized: User ID missing' });
            }

            const report = await GeneratedReport.findByPk(reportID);
            if (!report) {
                await transaction.rollback();
                logRequest({
                    req,
                    status: 404,
                    message: `Generated report ${reportID} not found`,
                    level: 'info',
                    service: 'report',
                    defaultRoute: 'reports'
                });
                return res.status(404).json({ error: 'Generated report not found' });
            }

            if (report.filePath) {
                const filePath = path.join(__dirname, '../reports', path.basename(report.filePath));
                try {
                    await fs.unlink(filePath);
                    logRequest({
                        req,
                        status: 200,
                        message: `Deleted file ${filePath} for report ${reportID}`,
                        level: 'info',
                        metadata: { userId, reportID, filePath },
                        service: 'report',
                        defaultRoute: 'reports'
                    });
                } catch (fileErr) {
                    logRequest({
                        req,
                        status: 404,
                        message: `File ${filePath} for report ${reportID} not found or could not be deleted: ${fileErr.message}`,
                        level: 'warn',
                        metadata: { userId, reportID, filePath, error: fileErr.message },
                        service: 'report',
                        defaultRoute: 'reports'
                    });
                }
            }

            const user = await User.findByPk(userId);
            const report0 = await GeneratedReport.findByPk(reportID);
            await report.destroy({ transaction });

            const cacheInstance = await cache();
            const redis = getRedisClient();
            await cacheInstance.invalidateByTag('reports');
            await cacheInstance.invalidate(`report:generated:${userId}`);
            await redis.set('reports:last_updated', Date.now().toString());
            await RedisUtils.publishEvent('cache:invalidate', 'reports');

            const requestID = uuidv4();
            await NotificationService.triggerNotification({
                event: 'report:deleted',
                data: { reportID },
                metadata: { deletedBy: req.user?.email || 'unknown' },
                dynamicRecipients: [],
                triggeredByUserID: userId,
                type: 'report',
                customMessage: `Generated report ${report0.reportType} deleted by user ${user.filename} ${user.lastname}`,
                requestID,
            });

            logRequest({
                req,
                res: { message: 'Generated report deleted successfully' },
                status: 200,
                message: `Deleted generated report ${reportID}`,
                level: 'info',
                metadata: { userId, reportID, requestID },
                service: 'report',
                defaultRoute: 'reports'
            });

            await transaction.commit();
            return res.status(200).json({ message: 'Generated report deleted successfully' });
        } catch (error) {
            await transaction.rollback();
            logRequest({
                req,
                error,
                status: 500,
                message: `Failed to delete generated report: ${error.message}`,
                level: 'error',
                service: 'report',
                defaultRoute: 'reports'
            });
            return res.status(500).json({ error: 'Failed to delete generated report' });
        }
    }
}

module.exports = ReportController;